//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RobotControl.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDR_MAINFRAME                   128
#define IDR_ROBOTCTYPE                  129
#define IDD_SIDEBAR                     130
#define IDD_INITHARDWARE                131
#define IDR_MENUCONTEXT                 132
#define IDD_PATHPLAN                    133
#define IDD_LINERPLANSETTING            134
#define IDD_AUTOPLANSETTING             135
#define IDD_HANDCONTROL                 136
#define IDD_DepthImg                    137
#define IDC_BUTTON_PMACOPEN             1000
#define IDC_EDIT_VELOCITY               1001
#define IDC_BUTTON_PMACCLOSE            1002
#define IDC_BUTTON_ZERO                 1003
#define IDC_BUTTON_MAKESURE             1004
#define IDC_BUTTON_RESET                1005
#define IDC_EDIT_ABSOPOSITION           1006
#define IDC_EDIT_RELAPOSITION           1007
#define IDC_BUTTON_RUN2                 1008
#define IDC_BUTTON_RUN1                 1009
#define IDC_LIST_MODULE                 1010
#define IDC_BUTTON_SCAN                 1011
#define IDC_BUTTON_TELEMETRY            1012
#define IDC_RADIO_POSITION              1013
#define IDC_RADIO_VELOCITY              1014
#define IDC_RADIO_CURRENT               1015
#define IDC_EDIT_POSMODULE1             1016
#define IDC_EDIT_VELMODULE1             1017
#define IDC_EDIT_CURMODULE1             1018
#define IDC_EDIT_ACCMODULE1             1018
#define IDC_BUTTON_GO1                  1019
#define IDC_EDIT_POSMODULE2             1020
#define IDC_EDIT_VELMODULE2             1021
#define IDC_EDIT_CURMODULE2             1022
#define IDC_EDIT_ACCMODULE2             1022
#define IDC_BUTTON_GO2                  1023
#define IDC_EDIT_POSMODULE3             1024
#define IDC_EDIT_VELMODULE3             1025
#define IDC_EDIT_CURMODULE3             1026
#define IDC_EDIT_ACCMODULE3             1026
#define IDC_BUTTON_GO3                  1027
#define IDC_EDIT1_POSMODULE4            1028
#define IDC_EDIT_POSMODULE4             1028
#define IDC_EDIT_VELMODULE4             1029
#define IDC_EDIT_CURMODULE4             1030
#define IDC_EDIT_ACCMODULE4             1030
#define IDC_BUTTON_GO4                  1031
#define IDC_EDIT1_POSMODULE5            1032
#define IDC_EDIT_POSMODULE5             1032
#define IDC_EDIT_VELMODULE5             1033
#define IDC_EDIT_CURMODULE5             1034
#define IDC_EDIT_ACCMODULE5             1034
#define IDC_BUTTON_GO5                  1035
#define IDC_EDIT1_POSMODULE6            1036
#define IDC_EDIT_POSMODULE6             1036
#define IDC_EDIT_VELMODULE6             1037
#define IDC_EDIT_CURMODULE6             1038
#define IDC_EDIT_ACCMODULE6             1038
#define IDC_BUTTON_GO6                  1039
#define IDC_STATIC_PMACMAIL             1040
#define IDC_BUTTON_EXIT                 1041
#define IDC_RADIO_MODULE1               1042
#define IDC_RADIO_MODULE2               1043
#define IDC_RADIO_MODULE3               1044
#define IDC_RADIO_MODULE4               1045
#define IDC_RADIO_MODULE5               1046
#define IDC_RADIO_MODULE6               1047
#define IDC_EDIT_POSMODULE7             1048
#define IDC_EDIT_VELMODULE7             1049
#define IDC_EDIT_ACCMODULE7             1050
#define IDC_BUTTON_GO7                  1051
#define IDC_RADIO_MODULE7               1052
#define IDC_STATIC_ACTPOS               1053
#define IDC_STATIC_ACTVEL               1054
#define IDC_STATIC_DELTAPOS             1055
#define IDC_STATIC_DELTAPOS2            1056
#define IDC_EDIT_JNT1                   1056
#define IDC_SLIDER_JNT1                 1057
#define IDC_EDIT_JNT2                   1058
#define IDC_SLIDER_JNT2                 1059
#define IDC_EDIT_JNT3                   1060
#define IDC_SLIDER_JNT3                 1061
#define IDC_EDIT_JNT4                   1062
#define IDC_SLIDER_JNT4                 1063
#define IDC_EDIT_JNT5                   1064
#define IDC_SLIDER_JNT5                 1065
#define IDC_EDIT_JNT6                   1066
#define IDC_SLIDER_JNT6                 1067
#define IDC_BUTTON_SET                  1068
#define IDC_EDIT_PLANTIME               1069
#define IDC_EDIT_JNT7                   1070
#define IDC_SLIDER_JNT7                 1071
#define IDC_EDIT_ACCTIME                1072
#define IDC_RADIO_LINEARPLAN            1073
#define IDC_RADIO_ARCPLAN               1074
#define IDC_EDIT_PXINT                  1074
#define IDC_RADIO_HANDCONTROL           1074
#define IDC_RADIO_CONCURPLAN            1075
#define IDC_EDIT_PYINT                  1075
#define IDC_RADIO_HANDCONTROL2          1075
#define IDC_RADIO_AUTOPLAN              1076
#define IDC_EDIT_PZINT                  1076
#define IDC_RADIO_JNTPLAN               1077
#define IDC_EDIT_AIFINT                 1077
#define IDC_RADIO_PROGRAMM              1078
#define IDC_EDIT_BITINT                 1078
#define IDC_BUTTON_INIT                 1079
#define IDC_EDIT_GAMINT                 1079
#define IDC_BUTTON_INIOK                1080
#define IDC_EDIT_PXEND                  1080
#define IDC_BUTTON_RUN                  1081
#define IDC_EDIT_PYEND                  1081
#define IDC_BUTTON_STOP                 1082
#define IDC_EDIT_PZEND                  1082
#define IDC_EDIT_AIFEND                 1083
#define IDC_EDIT_JNT0                   1083
#define IDC_EDIT_BITEND                 1084
#define IDC_SLIDER_JNT0                 1084
#define IDC_EDIT_GAMEND                 1085
#define IDC_BUTTON_SAVEDATA             1085
#define IDC_BUTTON_IMPORT               1087
#define IDC_PXINT                       1088
#define IDC_PYINT                       1089
#define IDC_PZINT                       1090
#define IDC_AIFINT                      1091
#define IDC_BITINT                      1092
#define IDC_GAMINT                      1093
#define IDC_PXEND                       1094
#define IDC_PYEND                       1095
#define IDC_PZEND                       1096
#define IDC_AIFEND                      1097
#define IDC_BITEND                      1098
#define IDC_GAMEND                      1099
#define IDC_CHECK_EYE                   1100
#define IDC_RAD_CAPORIENTX              1101
#define IDC_RAD_CAPORIENTXF             1102
#define IDC_RAD_CAPORIENTZ              1103
#define IDC_RAD_CAPORIENTY              1104
#define IDC_RAD_CAPORIENTYF             1105
#define IDC_RAD_CAPORIENTZF             1106
#define IDC_RADIO_AUTOSTRPLAN           1107
#define IDC_RADIO_AUTOCURPLAN           1108
#define IDC_BTN_IMPORT                  1109
#define IDC_BTN_SET                     1110
#define IDC_RADIO_TRANSLATE             1112
#define IDC_RADIO_ROTATE                1113
#define IDC_SLIDER_VELVALUE             1114
#define IDC_BUTTON_XTRANSP              1115
#define IDC_BUTTON_YTRANSP              1116
#define IDC_BUTTON_ZTRANSP              1117
#define IDC_BUTTON_XTRANSI              1118
#define IDC_BUTTON_YTRANSI              1119
#define IDC_BUTTON_ZTRANSI              1120
#define IDC_BUTTON_XROTP                1121
#define IDC_BUTTON_YROTP                1122
#define IDC_BUTTON_ZROTP                1123
#define IDC_BUTTON_XROTI                1124
#define IDC_BUTTON_YROTI                1125
#define IDC_BUTTON_ZROTI                1126
#define IDC_CHECK_REMOTECONTROL         1127
#define IDC_BUTTON_STOPH                1128
#define IDC_BUTTON_RESETH               1129
#define IDC_HOTKEY1                     1132
#define IDC_BUTTON_SETH                 1132
#define IDC_RADIO_SUMU                  1133
#define IDC_RADIO_JXB                   1134
#define IDC_KEY_CONTROL                 1141
#define IDC_CAMERA                      1142
#define IDC_BUTTON_CATCHMODE            1145
#define IDC_BUTTON_SHUTCAMERA           1147
#define IDC_PARAMETER_TAB               2000
#define IDM_INITMODULE                  32771
#define IDM_RESETMODULE                 32772
#define IDM_HALTMODULE                  32773
#define IDM_0CURRENTMODULE              32774
#define ID_CONNECT_COMPUTER             32775
#define ID_STOP_CONNECT                 32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1148
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
